CC = gcc
CFLAGS = -Wall -g

TARFILES = Makefile scanner.mll parser.mly ast.mli calc.ml

OBJS = parser.cmo scanner.cmo calc.cmo
ALLOBJS = ast.cmo cast.cmo stubs.cmo sast.cmo parser.cmo scanner.cmo compile.cmo execute.cmo \
	iast.cmo iparser.cmo iscanner.cmo imports.cmo pltree.cmo

pltree: $(ALLOBJS)
	ocamlc -o pltree $(ALLOBJS)

calc : $(OBJS)
	ocamlc -o calc $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

iscanner.ml : iscanner.mll
	ocamllex iscanner.mll

iparser.ml iparser.mli : iparser.mly
	ocamlyacc iparser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<


.PHONY : menhir
menhir:
	menhir -v parser.mly

.SECONDARY:

%: %.o
	$(CC) $(CFLAGS) -o $@ $<

%.o: %.c %.h
	$(CC) $(CFLAGS) -c $< -o $@

%.c: %.tree pltree
	./pltree $< $@

calculator.tar.gz : $(TARFILES)
	cd .. && tar zcf calculator/calculator.tar.gz $(TARFILES:%=calculator/%)


/usr/local/bin/pltree_std/stdio.tree: 
	mkdir /usr/local/bin/pltree_std
	cp stdio.tree /usr/local/bin/pltree_std

.PHONY: install
install: pltree /usr/local/bin/pltree_std/stdio.tree
	cp pltree /usr/local/bin

.PHONY : clean
clean :
	rm -f calc pltree parser.ml parser.mli scanner.ml
	rm -f iparser.ml iparser.mli iscanner.ml
	rm -f *.cmo *.cmi *.o *.tmp *.c
	rm -f hello func_test gcd tree fact ll fibo pretty_tree
	rm -f *.automaton *.conflicts

# Generated by ocamldep *.ml *.mli
ast.cmo :
ast.cmx :
calc.cmo : scanner.cmo parser.cmi ast.cmo
calc.cmx : scanner.cmx parser.cmx ast.cmx
cast.cmo :
cast.cmx :
compile.cmo : sast.cmo ast.cmo
compile.cmx : sast.cmx ast.cmx
execute.cmo : stubs.cmo sast.cmo cast.cmo
execute.cmx : stubs.cmx sast.cmx cast.cmx
iast.cmo :
iast.cmx :
imports.cmo : iscanner.cmo iparser.cmi iast.cmo
imports.cmx : iscanner.cmx iparser.cmx iast.cmx
iparser.cmo : iast.cmo iparser.cmi
iparser.cmx : iast.cmx iparser.cmi
iscanner.cmo : iparser.cmi
iscanner.cmx : iparser.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
pltree.cmo : scanner.cmo parser.cmi imports.cmo execute.cmo compile.cmo
pltree.cmx : scanner.cmx parser.cmx imports.cmx execute.cmx compile.cmx
read.cmo : scanner.cmo parser.cmi ast.cmo
read.cmx : scanner.cmx parser.cmx ast.cmx
read_tree.cmo : scanner.cmo parser.cmi
read_tree.cmx : scanner.cmx parser.cmx
sast.cmo :
sast.cmx :
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
stubs.cmo :
stubs.cmx :
iparser.cmi : iast.cmo
parser.cmi : ast.cmo
